spring:
  datasource:
    username: magma
    password: magma
    url: jdbc:postgresql://localhost:5432/magma
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true


server:
  port: 8080
#jwt:
#  secret:
#    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
#    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
